export interface Lesson {
  id: string
  title: string
  completed: boolean
}

export interface Module {
  id: string
  pillarId: string
  number: number
  title: string
  description: string
  emoji: string
  lessons: Lesson[]
  unlocked: boolean
  completed: boolean
}

export interface Pillar {
  id: string
  number: number
  title: string
  description: string
  emoji: string
  modules: Module[]
}

function makeLessons(pillarId: string, moduleNum: number, titles: string[]): Lesson[] {
  return titles.map((title, i) => ({
    id: `p${pillarId}-m${moduleNum}-l${i + 1}`,
    title,
    completed: false,
  }))
}

export const pillars: Pillar[] = [

  // ─────────────────────────────────────────
  // PILLAR 1 — MONEY & FINANCE
  // ─────────────────────────────────────────
  {
    id: '1',
    number: 1,
    title: 'Money & Finance',
    description: 'Paychecks, taxes, budgeting, debt, credit, banking, investing, and building long-term wealth.',
    emoji: '💰',
    modules: [
      {
        id: '1-1', pillarId: '1', number: 1,
        title: 'Your First Paycheck Decoded',
        description: 'Understanding what your paycheck actually says and where your money goes before it hits your account.',
        emoji: '💵', unlocked: true, completed: false,
        lessons: makeLessons('1', 1, [
          'What Happened to My Money?',
          'Gross Pay vs. Net Pay',
          'Federal & State Taxes Explained',
          'FICA — Social Security & Medicare',
          'Voluntary Deductions — Insurance, 401k, HSA',
          'How to Read Every Line on Your Pay Stub',
          'Hourly vs. Salary — What\'s the Difference',
          'What to Do the Day You Get Paid',
        ]),
      },
      {
        id: '1-2', pillarId: '1', number: 2,
        title: 'Taxes Without the Panic',
        description: 'Demystifying the tax system — what you owe, why you owe it, and how to file without losing your mind.',
        emoji: '🧾', unlocked: true, completed: false,
        lessons: makeLessons('1', 2, [
  'Why We Pay Taxes',
  'W-2 vs. 1099 — Which One Are You',
  'Independent vs. Dependent — What\'s Your Filing Status',
  'Tax Brackets Explained',
  'Deductions & Credits — What Lowers Your Bill',
  'How to File Your Taxes',
  'Filing an Amendment — How to Fix a Mistake',
  'What Happens If You Don\'t File',
  'Getting a Refund vs. Owing Money',
  'Quarterly Taxes for Freelancers & Self-Employed',
  'What April 15 Actually Means',
]),
      },
      {
        id: '1-3', pillarId: '1', number: 3,
        title: 'Building Your First Budget',
        description: 'Creating a spending plan that actually works for your life and income.',
        emoji: '📊', unlocked: true, completed: false,
        lessons: makeLessons('1', 3, [
          'Why Budgeting Changes Everything',
          'The 50/30/20 Rule',
          'Fixed vs. Variable Expenses',
          'How to Track Your Spending',
          'Building Your First Budget Step by Step',
          'What to Do When You Go Over Budget',
          'Budgeting Apps & Tools',
          'Adjusting Your Budget as Life Changes',
        ]),
      },
      {
        id: '1-4', pillarId: '1', number: 4,
        title: 'Banking Basics',
        description: 'Understanding how banks work, what accounts you need, and how to use them without getting hit with fees.',
        emoji: '🏦', unlocked: true, completed: false,
        lessons: makeLessons('1', 4, [
          'Checking vs. Savings — What\'s the Difference',
          'How to Open a Bank Account',
          'Understanding Bank Fees',
          'Online Banks vs. Traditional Banks',
          'Credit Unions — What They Are & Why They Matter',
          'Direct Deposit & Automatic Payments',
          'Overdrafts — What They Are & How to Avoid Them',
          'How to Read a Bank Statement',
        ]),
      },
      {
        id: '1-5', pillarId: '1', number: 5,
        title: 'Emergency Funds',
        description: 'Building a financial safety net so one bad week doesn\'t turn into a financial disaster.',
        emoji: '🛡️', unlocked: true, completed: false,
        lessons: makeLessons('1', 5, [
          'What Is an Emergency Fund',
          'Why $1,000 Changes Everything',
          'How Much Should You Save',
          'Where to Keep Your Emergency Fund',
          'How to Build It When You Have Nothing',
          'What Counts as a Real Emergency',
          'Rebuilding After You Use It',
          'The Psychology of Having a Safety Net',
        ]),
      },
      {
        id: '1-6', pillarId: '1', number: 6,
        title: 'Getting Out of Debt',
        description: 'Understanding your debt, making a plan, and actually following through on it.',
        emoji: '⛓️', unlocked: true, completed: false,
        lessons: makeLessons('1', 6, [
          'Understanding Your Debt — Types & Interest',
          'The True Cost of Minimum Payments',
          'The Avalanche Method',
          'The Snowball Method',
          'Which Method Is Right for You',
          'Negotiating With Creditors',
          'Debt Consolidation — Pros & Cons',
          'What Happens If You Ignore Debt',
          'Life After Debt — What to Do Next',
        ]),
      },
      {
        id: '1-7', pillarId: '1', number: 7,
        title: 'Understanding Credit',
        description: 'What your credit score is, what moves it, and how to build it from zero.',
        emoji: '📈', unlocked: true, completed: false,
        lessons: makeLessons('1', 7, [
          'What Is a Credit Score',
          'The Five Factors That Affect Your Score',
          'How to Check Your Credit for Free',
          'Building Credit From Scratch',
          'Secured Cards & Credit Builder Loans',
          'What Hurts Your Credit',
          'Disputing Errors on Your Credit Report',
          'How Long Negative Items Stay on Your Report',
          'What a Good Score Gets You',
        ]),
      },
      {
        id: '1-8', pillarId: '1', number: 8,
        title: 'Insurance 101',
        description: 'Understanding the types of insurance you need and what you\'re actually paying for.',
        emoji: '☂️', unlocked: true, completed: false,
        lessons: makeLessons('1', 8, [
          'Why Insurance Exists',
          'Premiums, Deductibles & Copays Explained',
          'Health Insurance Basics',
          'Life Insurance — Do You Need It',
          'Renters Insurance — What It Covers & Why It\'s Worth It',
          'Understanding Your Explanation of Benefits (EOB)',
          'What Happens If You\'re Uninsured',
          'How to Shop for Insurance',
        ]),
      },
      {
        id: '1-9', pillarId: '1', number: 9,
        title: 'Investing for Beginners',
        description: 'Where to start with investing, why it matters now, and how to make your money work for you.',
        emoji: '💹', unlocked: true, completed: false,
        lessons: makeLessons('1', 9, [
          'Why Investing Matters & Why to Start Now',
          'Risk vs. Reward — Understanding the Basics',
          'Stocks, Bonds & Index Funds Explained',
          'Your 401k — What It Is & How to Use It',
          'IRA vs. Roth IRA — Which Is Right for You',
          'Compound Interest — The Most Powerful Force in Finance',
          'How to Open a Brokerage Account',
          'Dollar Cost Averaging',
          'Common Investing Mistakes to Avoid',
        ]),
      },
      {
        id: '1-10', pillarId: '1', number: 10,
        title: 'Building Long-Term Wealth',
        description: 'Moving beyond survival mode and building a financial future that lasts.',
        emoji: '🏗️', unlocked: true, completed: false,
        lessons: makeLessons('1', 10, [
          'The Wealth Mindset',
          'Net Worth — What It Is & How to Track It',
          'Multiple Income Streams',
          'Real Estate as Wealth Building',
          'Retirement Planning in Your 20s & 30s',
          'Estate Planning Basics — Wills & Beneficiaries',
          'Teaching Your Kids About Money',
          'Generational Wealth — What It Is & How to Start It',
        ]),
      },
      {
        id: '1-11', pillarId: '1', number: 11,
        title: 'Side Income & Freelancing',
        description: 'How to make money outside your 9-5, stay legal about it, and actually grow it.',
        emoji: '💼', unlocked: true, completed: false,
        lessons: makeLessons('1', 11, [
          'Why Side Income Changes the Game',
          'Finding What You Can Offer',
          'Freelancing vs. Gig Work vs. Passive Income',
          'Setting Your Rates',
          'Finding Your First Client',
          'Taxes as a Freelancer — What You Need to Know',
          'Separating Business & Personal Money',
          'Growing Your Side Income Into Something More',
        ]),
      },
      {
        id: '1-12', pillarId: '1', number: 12,
        title: 'Subscriptions & Spending Leaks',
        description: 'Finding the money you\'re losing every month without realizing it.',
        emoji: '🔍', unlocked: true, completed: false,
        lessons: makeLessons('1', 12, [
          'What Are Spending Leaks',
          'Auditing Your Subscriptions',
          'The Psychology of Recurring Charges',
          'How to Cancel Without the Runaround',
          'Impulse Spending — Why It Happens & How to Stop',
          'Want vs. Need — Getting Honest With Yourself',
          'Building a Spending Values System',
          'What to Do With the Money You Find',
        ]),
      },
      {
        id: '1-13', pillarId: '1', number: 13,
        title: 'Negotiating Your Salary',
        description: 'How to ask for more money and actually get it — at a new job or your current one.',
        emoji: '🤝', unlocked: true, completed: false,
        lessons: makeLessons('1', 13, [
          'Why Most People Never Negotiate',
          'Knowing Your Market Value',
          'How to Research Salary Ranges',
          'The Conversation — What to Say Word for Word',
          'Negotiating Benefits Beyond Salary',
          'What to Do If They Say No',
          'Asking for a Raise at Your Current Job',
          'Knowing When to Walk Away',
        ]),
      },
      {
        id: '1-14', pillarId: '1', number: 14,
        title: 'Understanding Your Benefits Package',
        description: 'Decoding what your employer is actually offering you and making sure you use all of it.',
        emoji: '🎁', unlocked: true, completed: false,
        lessons: makeLessons('1', 14, [
          'What Is a Benefits Package',
          'Health Insurance Through Your Employer',
          '401k Matching — Free Money You Might Be Leaving Behind',
          'HSA & FSA — What They Are & How to Use Them',
          'PTO, Sick Days & Leave Policies',
          'Life & Disability Insurance Through Work',
          'Employee Assistance Programs (EAPs)',
          'How to Choose Benefits During Open Enrollment',
        ]),
      },
      {
        id: '1-15', pillarId: '1', number: 15,
        title: 'Sending & Receiving Money Safely',
        description: 'How to move money without getting scammed, overcharged, or caught off guard.',
        emoji: '💸', unlocked: true, completed: false,
        lessons: makeLessons('1', 15, [
          'Venmo, Cash App & Zelle — How They Actually Work',
          'Wire Transfers & Bank Transfers',
          'Common Money Scams & How to Spot Them',
          'What to Do If You Get Scammed',
          'Sending Money Internationally',
          'Payment Protection — What\'s Covered & What\'s Not',
          'Keeping Your Accounts Secure',
          'Red Flags to Never Ignore',
        ]),
      },
      {
        id: '1-16', pillarId: '1', number: 16,
        title: 'Protecting Your Identity',
        description: 'What identity theft is, how it happens, and how to protect yourself before and after.',
        emoji: '🔐', unlocked: true, completed: false,
        lessons: makeLessons('1', 16, [
          'What Is Identity Theft',
          'How Thieves Get Your Information',
          'Credit Freezes & Fraud Alerts',
          'Monitoring Your Credit & Accounts',
          'Safe Online & Offline Habits',
          'What to Do If Your Identity Is Stolen',
          'Recovering Your Credit After Theft',
          'Protecting Your Kids\' Identity',
        ]),
      },
      {
        id: '1-17', pillarId: '1', number: 17,
        title: 'Understanding Loans',
        description: 'Breaking down every type of loan, how interest works, and how to borrow without destroying your future.',
        emoji: '🏛️', unlocked: true, completed: false,
        lessons: makeLessons('1', 17, [
          'What Is a Loan & How Does Interest Work',
          'Student Loans — Federal vs. Private',
          'Student Loan Repayment Plans',
          'Personal Loans — When They Make Sense',
          'Auto Loans — How They Work',
          'Payday Loans — Why to Avoid Them',
          'How to Compare Loan Offers',
          'What Happens If You Default',
        ]),
      },
      {
        id: '1-18', pillarId: '1', number: 18,
        title: 'Buying a Car',
        description: 'How to navigate one of the biggest purchases you\'ll make without getting taken advantage of.',
        emoji: '🚗', unlocked: true, completed: false,
        lessons: makeLessons('1', 18, [
          'New vs. Used — The Real Math',
          'How to Research a Car',
          'Getting Pre-Approved for a Loan Before You Shop',
          'Dealership Tactics & How to Handle Them',
          'Reading the Contract Before You Sign',
          'Total Cost of Ownership — Insurance, Gas, Maintenance',
          'Private Party Sales vs. Dealerships',
          'When to Walk Away',
        ]),
      },
      {
        id: '1-19', pillarId: '1', number: 19,
        title: 'Filing for Financial Aid',
        description: 'Understanding FAFSA, grants, scholarships, and every dollar of help available to you.',
        emoji: '🎓', unlocked: true, completed: false,
        lessons: makeLessons('1', 19, [
          'What Financial Aid Actually Is',
          'How FAFSA Works',
          'Grants vs. Loans vs. Scholarships',
          'What Counts as Income on Your Application',
          'Dependency Status — Are You Independent',
          'How to Find Scholarships',
          'What to Do If Your Aid Changes',
          'Appealing Your Financial Aid Package',
        ]),
      },
      {
        id: '1-20', pillarId: '1', number: 20,
        title: 'How to Read a Contract',
        description: 'Understanding what you\'re actually agreeing to before you sign anything.',
        emoji: '📋', unlocked: true, completed: false,
        lessons: makeLessons('1', 20, [
          'Why Contracts Matter',
          'The Parts of Every Contract',
          'Red Flags to Look For',
          'Common Contract Traps',
          'Employment Contracts — What to Watch For',
          'Lease Agreements — What to Watch For',
          'Service Agreements & Terms of Service',
          'When to Ask a Lawyer',
        ]),
      },
      {
        id: '1-21', pillarId: '1', number: 21,
        title: 'Financial Goals & Milestones',
        description: 'Setting real financial goals, making a plan to hit them, and tracking your progress.',
        emoji: '🎯', unlocked: true, completed: false,
        lessons: makeLessons('1', 21, [
          'Why Goals Without Plans Are Just Wishes',
          'Short-Term vs. Long-Term Goals',
          'The SMART Goal Framework for Money',
          'Saving for a Car',
          'Saving for a Home',
          'Saving for a Life Event',
          'Tracking Progress Without Losing Motivation',
          'Celebrating Milestones Without Blowing Your Budget',
        ]),
      },
      {
        id: '1-22', pillarId: '1', number: 22,
        title: 'Renting vs. Buying a Home',
        description: 'The real financial math behind one of the biggest decisions you\'ll ever make.',
        emoji: '🏠', unlocked: true, completed: false,
        lessons: makeLessons('1', 22, [
          'The Rent vs. Buy Debate',
          'True Cost of Homeownership',
          'How Mortgages Work',
          'How Much House Can You Actually Afford',
          'The Hidden Costs of Buying',
          'When Renting Makes More Sense',
          'Building Equity vs. Building Flexibility',
          'Getting Mortgage-Ready — What to Do Now',
        ]),
      },
    ],
  },

  // ─────────────────────────────────────────
  // PILLAR 2 — INDEPENDENT LIVING
  // ─────────────────────────────────────────
  {
    id: '2',
    number: 2,
    title: 'Independent Living',
    description: 'Renting, utilities, groceries, cooking, car insurance, home maintenance, and everything that comes with living on your own.',
    emoji: '🏡',
    modules: [
      {
        id: '2-1', pillarId: '2', number: 1,
        title: 'Finding Your First Apartment',
        description: 'How to search for, apply for, and land your first apartment without getting taken advantage of.',
        emoji: '🔑', unlocked: true, completed: false,
        lessons: makeLessons('2', 1, [
          'Where to Start Your Search',
          'What to Look for on a Tour',
          'Understanding Application Requirements',
          'Credit & Income Requirements — What Landlords Want',
          'Application Fees & What They Cover',
          'Red Flags in Listings & Tours',
          'How to Negotiate Rent',
          'What Happens After You Apply',
        ]),
      },
      {
        id: '2-2', pillarId: '2', number: 2,
        title: 'Understanding Your Lease',
        description: 'Breaking down every section of your lease so you know exactly what you\'re agreeing to.',
        emoji: '📄', unlocked: true, completed: false,
        lessons: makeLessons('2', 2, [
          'What a Lease Actually Is',
          'The Key Sections of Every Lease',
          'Month-to-Month vs. Fixed Term',
          'Security Deposits — What They Cover & How to Get Yours Back',
          'Pet Clauses, Guest Policies & Restrictions',
          'What Happens If You Break Your Lease',
          'Lease Renewals & Rent Increases',
          'What to Do Before You Sign',
        ]),
      },
      {
        id: '2-3', pillarId: '2', number: 3,
        title: 'Dealing With Landlords',
        description: 'How to communicate with, handle problems with, and protect yourself from your landlord.',
        emoji: '🏘️', unlocked: true, completed: false,
        lessons: makeLessons('2', 3, [
          'Setting the Relationship Up Right',
          'How to Report Maintenance Issues',
          'What Your Landlord Is Required to Fix',
          'Documenting Everything — Why It Matters',
          'When Your Landlord Isn\'t Responding',
          'Retaliation — What It Is & What to Do',
          'When to Involve a Lawyer or Housing Authority',
          'Moving Out Without Losing Your Deposit',
        ]),
      },
      {
        id: '2-4', pillarId: '2', number: 4,
        title: 'Setting Up Utilities',
        description: 'What utilities you need, how to set them up, and how to keep costs manageable.',
        emoji: '⚡', unlocked: true, completed: false,
        lessons: makeLessons('2', 4, [
          'What Are Utilities',
          'Electric, Gas & Water — How Each Works',
          'How to Set Up Utilities in Your Name',
          'Internet — Choosing a Plan',
          'Understanding Your Utility Bills',
          'How to Lower Your Utility Costs',
          'What Happens If You Miss a Payment',
          'Utilities in Shared Living Situations',
        ]),
      },
      {
        id: '2-5', pillarId: '2', number: 5,
        title: 'Health Insurance Basics',
        description: 'Understanding your health insurance options, what your plan covers, and how to actually use it.',
        emoji: '🏥', unlocked: true, completed: false,
        lessons: makeLessons('2', 5, [
          'Why Health Insurance Matters',
          'Types of Health Insurance Plans',
          'Premiums, Deductibles, Copays & Out-of-Pocket Max',
          'In-Network vs. Out-of-Network',
          'Getting Insurance Through Your Job',
          'Marketplace Insurance — Healthcare.gov',
          'Medicaid & CHIP — Who Qualifies',
          'What to Do If You Have No Insurance',
          'How to Use Your Insurance When You Need It',
        ]),
      },
      {
        id: '2-6', pillarId: '2', number: 6,
        title: 'Car Insurance Basics',
        description: 'What car insurance covers, what you\'re required to have, and how to get the best rate.',
        emoji: '🚘', unlocked: true, completed: false,
        lessons: makeLessons('2', 6, [
          'Why Car Insurance Is Required',
          'Types of Coverage — Liability, Collision, Comprehensive',
          'What Your Policy Actually Covers',
          'How Premiums Are Calculated',
          'Shopping for the Best Rate',
          'What to Do After an Accident',
          'Filing a Claim — Step by Step',
          'How Accidents Affect Your Rate',
        ]),
      },
      {
        id: '2-7', pillarId: '2', number: 7,
        title: 'Grocery Shopping on a Budget',
        description: 'How to eat well, waste less, and spend less at the grocery store.',
        emoji: '🛒', unlocked: true, completed: false,
        lessons: makeLessons('2', 7, [
          'Planning Before You Shop',
          'Making a Grocery List That Works',
          'Understanding Unit Prices',
          'Store Brands vs. Name Brands',
          'How to Use Sales & Coupons Without Overdoing It',
          'Avoiding Food Waste',
          'Shopping at Different Store Types',
          'Stocking a Pantry From Scratch',
        ]),
      },
      {
        id: '2-8', pillarId: '2', number: 8,
        title: 'Cooking Basics',
        description: 'Learning to cook simple, affordable, real meals from scratch.',
        emoji: '🍳', unlocked: true, completed: false,
        lessons: makeLessons('2', 8, [
          'Essential Kitchen Tools',
          'Kitchen Safety & Food Safety',
          'Basic Cooking Techniques Everyone Should Know',
          'Reading a Recipe',
          'Cooking Proteins — Chicken, Eggs, Ground Beef',
          'Cooking Carbs — Rice, Pasta, Potatoes',
          'Cooking Vegetables Without Ruining Them',
          'Building a Meal From What You Have',
        ]),
      },
      {
        id: '2-9', pillarId: '2', number: 9,
        title: 'Meal Planning',
        description: 'How to plan your meals for the week so you save time, money, and stress.',
        emoji: '📅', unlocked: true, completed: false,
        lessons: makeLessons('2', 9, [
          'Why Meal Planning Works',
          'How to Build a Weekly Meal Plan',
          'Batch Cooking & Meal Prep',
          'Breakfast, Lunch & Dinner on a Budget',
          'Planning Around Sales & What\'s in Season',
          'Meal Planning for One or Two People',
          'Using Leftovers Intentionally',
          'Adapting When Plans Change',
        ]),
      },
      {
        id: '2-10', pillarId: '2', number: 10,
        title: 'Laundry & Clothing Care',
        description: 'How to wash, dry, and care for your clothes so they last.',
        emoji: '👕', unlocked: true, completed: false,
        lessons: makeLessons('2', 10, [
          'Reading Clothing Labels',
          'Sorting Your Laundry',
          'Choosing the Right Wash Settings',
          'Detergent, Fabric Softener & Stain Removers',
          'Drying — Machine vs. Air Dry',
          'Ironing & Steaming Basics',
          'Storing Clothes Properly',
          'Basic Clothing Repairs — Buttons, Hems & Tears',
        ]),
      },
      {
        id: '2-11', pillarId: '2', number: 11,
        title: 'Cleaning & Home Maintenance',
        description: 'How to keep your living space clean, functional, and in good shape.',
        emoji: '🧹', unlocked: true, completed: false,
        lessons: makeLessons('2', 11, [
          'Building a Cleaning Routine',
          'Cleaning Products — What You Actually Need',
          'Room by Room Cleaning Guide',
          'Deep Cleaning vs. Regular Maintenance',
          'Basic Home Repairs You Can Do Yourself',
          'When to Call a Professional',
          'Pest Prevention & What to Do If You Have Pests',
          'Seasonal Maintenance Checklist',
        ]),
      },
      {
        id: '2-12', pillarId: '2', number: 12,
        title: 'Moving — What to Do, What It Costs',
        description: 'Planning and executing a move without losing your mind or your money.',
        emoji: '📦', unlocked: true, completed: false,
        lessons: makeLessons('2', 12, [
          'Planning Your Move Timeline',
          'True Cost of Moving',
          'DIY Move vs. Hiring Movers',
          'Packing — What to Keep, What to Toss',
          'Changing Your Address & Updating Your Info',
          'Setting Up Your New Place',
          'Moving With Pets or Kids',
          'What to Do If Something Gets Damaged',
        ]),
      },
      {
        id: '2-13', pillarId: '2', number: 13,
        title: 'Setting Up Your Home',
        description: 'Turning an empty space into a functional, comfortable place to live on a budget.',
        emoji: '🛋️', unlocked: true, completed: false,
        lessons: makeLessons('2', 13, [
          'The Essentials You Need First',
          'Furniture on a Budget — New, Used & Free',
          'Kitchen Setup From Scratch',
          'Bedroom & Bathroom Essentials',
          'Organization Systems That Work',
          'Making It Feel Like Home Without Spending Much',
          'Safety — Smoke Detectors, Locks & Emergency Supplies',
          'Building Up Over Time',
        ]),
      },
      {
        id: '2-14', pillarId: '2', number: 14,
        title: 'Phone Plans & Contracts',
        description: 'Understanding your phone plan, avoiding traps, and getting the best deal.',
        emoji: '📱', unlocked: true, completed: false,
        lessons: makeLessons('2', 14, [
          'Prepaid vs. Postpaid Plans',
          'The Big Carriers vs. MVNOs',
          'Understanding Your Phone Bill',
          'Device Financing — What It Actually Costs',
          'When & How to Switch Carriers',
          'International Plans & Travel',
          'Family Plans — Pros & Cons',
          'Protecting Your Phone & Data',
        ]),
      },
      {
        id: '2-15', pillarId: '2', number: 15,
        title: 'Knowing Your Rights as a Renter',
        description: 'What your landlord can and cannot do — and what you can do about it.',
        emoji: '⚖️', unlocked: true, completed: false,
        lessons: makeLessons('2', 15, [
          'The Basics of Tenant Rights',
          'Habitability — What Your Landlord Must Provide',
          'Privacy & Entry — When Can Your Landlord Come In',
          'Discrimination — What\'s Illegal',
          'Security Deposit Laws by State',
          'Eviction Process — What\'s Legal & What\'s Not',
          'How to File a Complaint',
          'Free Legal Resources for Renters',
        ]),
      },
      {
        id: '2-16', pillarId: '2', number: 16,
        title: 'Knowing Your Rights as a Consumer',
        description: 'How to protect yourself when you buy something, sign up for something, or get taken advantage of.',
        emoji: '🛡️', unlocked: true, completed: false,
        lessons: makeLessons('2', 16, [
          'Your Basic Consumer Rights',
          'Returns, Refunds & Exchanges',
          'Disputing a Charge on Your Card',
          'Warranties — What They Cover',
          'Debt Collection — What Collectors Can & Cannot Do',
          'Scams & Fraud — How to Report Them',
          'The FTC & CFPB — Who Protects You',
          'Small Claims Court — When & How to Use It',
        ]),
      },
      {
        id: '2-17', pillarId: '2', number: 17,
        title: 'Buying vs. Renting a Car',
        description: 'Whether to buy or rent, and how to make that decision based on your actual life.',
        emoji: '🚗', unlocked: true, completed: false,
        lessons: makeLessons('2', 17, [
          'Do You Actually Need a Car',
          'True Cost of Car Ownership',
          'Car Sharing & Rental Apps',
          'Public Transit as a Real Option',
          'When Buying Makes Sense',
          'When Renting or Leasing Makes Sense',
          'Budgeting for Transportation',
          'Making the Decision for Your Situation',
        ]),
      },
      {
        id: '2-18', pillarId: '2', number: 18,
        title: 'Basic Car Maintenance',
        description: 'What your car needs to keep running and how to handle basic issues yourself.',
        emoji: '🔧', unlocked: true, completed: false,
        lessons: makeLessons('2', 18, [
          'Understanding Your Dashboard Lights',
          'Oil Changes — What, When & How',
          'Tires — Pressure, Rotation & Replacement',
          'Brakes — When to Check & Replace',
          'Fluids — What to Check & How to Top Off',
          'Battery — Signs It\'s Dying & How to Jump Start',
          'Finding a Trustworthy Mechanic',
          'Keeping a Maintenance Log',
        ]),
      },
      {
        id: '2-19', pillarId: '2', number: 19,
        title: 'Pet Ownership Costs & Responsibilities',
        description: 'The real cost of owning a pet and how to afford it responsibly.',
        emoji: '🐾', unlocked: true, completed: false,
        lessons: makeLessons('2', 19, [
          'True Cost of Pet Ownership',
          'Adoption vs. Buying From a Breeder',
          'Vet Care — Routine & Emergency',
          'Pet Insurance — Is It Worth It',
          'Food, Supplies & Ongoing Costs',
          'Housing Rules & Pet Deposits',
          'Pet Care When You Travel or Work Long Hours',
          'What to Do If You Can\'t Afford Care',
        ]),
      },
      {
        id: '2-20', pillarId: '2', number: 20,
        title: 'Time Management & Adult Scheduling',
        description: 'How to manage your time, keep track of responsibilities, and stop feeling overwhelmed.',
        emoji: '⏰', unlocked: true, completed: false,
        lessons: makeLessons('2', 20, [
          'Why Adult Life Feels So Overwhelming',
          'Building a Weekly Schedule',
          'Calendars, Planners & Apps That Help',
          'Prioritizing When Everything Feels Urgent',
          'Saying No Without Guilt',
          'Managing Deadlines & Due Dates',
          'Time Blocking & Focus Techniques',
          'Rest as Part of Your Schedule',
        ]),
      },
      {
        id: '2-21', pillarId: '2', number: 21,
        title: 'Building a Routine That Works',
        description: 'Creating morning, evening, and weekly routines that make your life easier.',
        emoji: '🌅', unlocked: true, completed: false,
        lessons: makeLessons('2', 21, [
          'Why Routines Reduce Mental Load',
          'Building a Morning Routine',
          'Building an Evening Routine',
          'Weekly Reset — What It Is & How to Do It',
          'Routines for People Who Hate Routines',
          'Adjusting When Life Gets Chaotic',
          'Habit Stacking — Building New Habits Onto Existing Ones',
          'Making Your Routine Sustainable Long-Term',
        ]),
      },
      {
        id: '2-22', pillarId: '2', number: 22,
        title: 'Cooking for One or Two',
        description: 'How to cook the right portions, avoid waste, and eat well when you\'re not cooking for a crowd.',
        emoji: '🥘', unlocked: true, completed: false,
        lessons: makeLessons('2', 22, [
          'The Challenge of Cooking Small',
          'Scaling Recipes Down',
          'Staple Meals for One or Two',
          'Batch Cooking for Small Households',
          'Freezer Meals — What Works & What Doesn\'t',
          'Eating Out vs. Cooking — Finding the Balance',
          'Quick Meals for Busy Days',
          'Building a Rotation of Go-To Recipes',
        ]),
      },
      {
        id: '2-23', pillarId: '2', number: 23,
        title: 'Home Safety & Emergency Preparedness',
        description: 'How to keep your home safe and know what to do when something goes wrong.',
        emoji: '🔥', unlocked: true, completed: false,
        lessons: makeLessons('2', 23, [
          'Fire Safety & Prevention',
          'What to Do If There\'s a Fire',
          'Carbon Monoxide — What It Is & How to Detect It',
          'Flood & Water Damage — Prevention & Response',
          'Power Outages — How to Prepare & Respond',
          'Building an Emergency Kit',
          'Natural Disaster Preparedness by Region',
          'Home Security Basics',
        ]),
      },
    ],
  },

  // ─────────────────────────────────────────
  // PILLAR 3 — MINDSET & WELLBEING
  // ─────────────────────────────────────────
  {
    id: '3',
    number: 3,
    title: 'Mindset & Wellbeing',
    description: 'Mental health, relationships, healthy habits, motivation, self-worth, community, and the inner work of being a person.',
    emoji: '🧠',
    modules: [
      {
        id: '3-1', pillarId: '3', number: 1,
        title: 'Understanding Your Mental Health',
        description: 'What mental health actually is, why it matters, and how to start paying attention to yours.',
        emoji: '🧠', unlocked: true, completed: false,
        lessons: makeLessons('3', 1, [
          'What Is Mental Health',
          'The Mental Health Spectrum',
          'Common Mental Health Conditions & What They Feel Like',
          'How Mental Health Affects Every Area of Life',
          'Stigma — Why It Exists & How to Fight It',
          'Checking In With Yourself',
          'When to Seek Help',
          'Mental Health as Ongoing Maintenance',
        ]),
      },
      {
        id: '3-2', pillarId: '3', number: 2,
        title: 'Managing Stress & Anxiety',
        description: 'Understanding where stress and anxiety come from and building tools to manage them.',
        emoji: '😮‍💨', unlocked: true, completed: false,
        lessons: makeLessons('3', 2, [
          'What Stress Actually Is',
          'Good Stress vs. Bad Stress',
          'What Anxiety Feels Like',
          'Triggers — Identifying Yours',
          'Breathing & Grounding Techniques',
          'The Role of Sleep, Food & Exercise in Stress',
          'When Anxiety Becomes a Disorder',
          'Building a Stress Management Toolkit',
        ]),
      },
      {
        id: '3-3', pillarId: '3', number: 3,
        title: 'Building Healthy Habits',
        description: 'How habits actually work and how to build ones that stick.',
        emoji: '🌱', unlocked: true, completed: false,
        lessons: makeLessons('3', 3, [
          'The Science of Habits',
          'The Habit Loop — Cue, Routine, Reward',
          'Starting Small — Why Tiny Changes Win',
          'Keystone Habits That Change Everything',
          'Tracking Your Habits',
          'What to Do When You Slip Up',
          'Breaking Bad Habits',
          'Building Habits That Last',
        ]),
      },
      {
        id: '3-4', pillarId: '3', number: 4,
        title: 'Sleep & Recovery',
        description: 'Why sleep is non-negotiable and how to actually get enough of it.',
        emoji: '😴', unlocked: true, completed: false,
        lessons: makeLessons('3', 4, [
          'What Happens When You Sleep',
          'How Much Sleep You Actually Need',
          'Sleep Debt — What It Is & How It Hurts You',
          'Building a Sleep Routine',
          'Your Sleep Environment',
          'Screens, Caffeine & Sleep Killers',
          'Insomnia — What It Is & What to Do',
          'Naps — When They Help & When They Don\'t',
        ]),
      },
      {
        id: '3-5', pillarId: '3', number: 5,
        title: 'Motivation & Self-Discipline',
        description: 'Understanding why motivation comes and goes and building discipline that doesn\'t rely on feeling like it.',
        emoji: '⚡', unlocked: true, completed: false,
        lessons: makeLessons('3', 5, [
          'The Myth of Constant Motivation',
          'Intrinsic vs. Extrinsic Motivation',
          'Why Discipline Beats Motivation',
          'Starting When You Don\'t Feel Like It',
          'Connecting to Your Why',
          'Momentum — How to Build & Keep It',
          'Dealing With Procrastination',
          'Rewarding Yourself in Ways That Work',
        ]),
      },
      {
        id: '3-6', pillarId: '3', number: 6,
        title: 'Self-Worth & Confidence',
        description: 'Where self-worth comes from, how it gets damaged, and how to rebuild it.',
        emoji: '💪', unlocked: true, completed: false,
        lessons: makeLessons('3', 6, [
          'What Is Self-Worth',
          'Where Low Self-Worth Comes From',
          'The Inner Critic — Recognizing & Quieting It',
          'Confidence vs. Self-Worth — What\'s the Difference',
          'Building Confidence Through Action',
          'Stopping Comparison',
          'Receiving Compliments & Criticism',
          'Building a Relationship With Yourself',
        ]),
      },
      {
        id: '3-7', pillarId: '3', number: 7,
        title: 'Setting Boundaries',
        description: 'What boundaries are, why they matter, and how to set them without destroying relationships.',
        emoji: '🚧', unlocked: true, completed: false,
        lessons: makeLessons('3', 7, [
          'What Are Boundaries',
          'Why People Struggle to Set Them',
          'Types of Boundaries — Physical, Emotional, Digital',
          'How to Identify Your Boundaries',
          'How to Communicate a Boundary',
          'When Boundaries Are Crossed',
          'Boundaries With Family',
          'Boundaries at Work',
        ]),
      },
      {
        id: '3-8', pillarId: '3', number: 8,
        title: 'Healthy Relationships',
        description: 'What healthy relationships look like and how to build and maintain them.',
        emoji: '💚', unlocked: true, completed: false,
        lessons: makeLessons('3', 8, [
          'What Makes a Relationship Healthy',
          'Communication — The Foundation of Everything',
          'Conflict Without Damage',
          'Trust — How It\'s Built & Broken',
          'Giving & Receiving in Relationships',
          'Friendships as an Adult',
          'Romantic Relationships — What to Look For',
          'When Relationships Change or End',
        ]),
      },
      {
        id: '3-9', pillarId: '3', number: 9,
        title: 'Toxic Relationships & How to Leave Them',
        description: 'Recognizing unhealthy dynamics and finding the strength and plan to leave.',
        emoji: '⚠️', unlocked: true, completed: false,
        lessons: makeLessons('3', 9, [
          'What Makes a Relationship Toxic',
          'Manipulation Tactics — Recognizing Them',
          'Gaslighting — What It Is & How It Works',
          'Why People Stay in Toxic Relationships',
          'Planning to Leave Safely',
          'The Emotional Process of Leaving',
          'Rebuilding After a Toxic Relationship',
          'Avoiding the Same Patterns',
        ]),
      },
      {
        id: '3-10', pillarId: '3', number: 10,
        title: 'Building Your Support System',
        description: 'How to identify, build, and maintain the people around you who genuinely have your back.',
        emoji: '🤝', unlocked: true, completed: false,
        lessons: makeLessons('3', 10, [
          'What Is a Support System',
          'Auditing Your Current Circle',
          'How to Make Friends as an Adult',
          'Deepening Existing Relationships',
          'Online Community vs. In-Person Connection',
          'Being a Good Support to Others',
          'When Your Support System Isn\'t Enough',
          'Professional Support as Part of Your System',
        ]),
      },
      {
        id: '3-11', pillarId: '3', number: 11,
        title: 'Asking for Help Without Shame',
        description: 'Why asking for help is hard, why it matters, and how to actually do it.',
        emoji: '🙋', unlocked: true, completed: false,
        lessons: makeLessons('3', 11, [
          'Why We Struggle to Ask for Help',
          'The Cost of Not Asking',
          'What Asking for Help Actually Looks Like',
          'How to Ask — Practically & Emotionally',
          'Asking for Help at Work',
          'Asking for Help From Family',
          'Asking for Professional Help',
          'Receiving Help Gracefully',
        ]),
      },
      {
        id: '3-12', pillarId: '3', number: 12,
        title: 'Community & Belonging',
        description: 'Why humans need community, how to find yours, and how to build something that lasts.',
        emoji: '🏘️', unlocked: true, completed: false,
        lessons: makeLessons('3', 12, [
          'Why Belonging Matters',
          'Finding Your People',
          'Community vs. Crowd',
          'Contributing to Your Community',
          'Faith Communities & Spiritual Connection',
          'Online Communities — Benefits & Limits',
          'Building Community Where You Live',
          'What to Do When You Feel Like You Don\'t Belong',
        ]),
      },
      {
        id: '3-13', pillarId: '3', number: 13,
        title: 'Grief & Loss',
        description: 'Understanding grief, how it actually works, and how to move through it.',
        emoji: '🕊️', unlocked: true, completed: false,
        lessons: makeLessons('3', 13, [
          'What Is Grief',
          'The Many Forms of Loss',
          'The Stages of Grief — What They Actually Mean',
          'Grief That Doesn\'t Look Like Sadness',
          'How Long Does Grief Last',
          'Supporting Someone Who Is Grieving',
          'Complicated Grief — When It Gets Stuck',
          'Finding Meaning After Loss',
        ]),
      },
      {
        id: '3-14', pillarId: '3', number: 14,
        title: 'Dealing With Failure & Rejection',
        description: 'How to process failure and rejection without letting them define you.',
        emoji: '🔄', unlocked: true, completed: false,
        lessons: makeLessons('3', 14, [
          'Why Failure Feels So Personal',
          'What Failure Actually Is',
          'Separating Your Worth From Your Results',
          'Processing Rejection Without Spiraling',
          'What You Can Learn From Failure',
          'Getting Back Up — Practically & Emotionally',
          'Normalizing Failure as Part of Growth',
          'Stories of People Who Failed Before They Succeeded',
        ]),
      },
      {
        id: '3-15', pillarId: '3', number: 15,
        title: 'Anger Management',
        description: 'Understanding anger, where it comes from, and how to handle it without hurting yourself or others.',
        emoji: '🌊', unlocked: true, completed: false,
        lessons: makeLessons('3', 15, [
          'What Anger Actually Is',
          'Where Your Anger Comes From',
          'Healthy vs. Unhealthy Anger Expression',
          'Physical Signs That Anger Is Building',
          'De-escalation Techniques',
          'Anger in Relationships',
          'When Anger Becomes a Problem',
          'Getting Professional Help for Anger',
        ]),
      },
      {
        id: '3-16', pillarId: '3', number: 16,
        title: 'Loneliness & Isolation',
        description: 'Understanding loneliness, why it\'s so common, and what to actually do about it.',
        emoji: '🌙', unlocked: true, completed: false,
        lessons: makeLessons('3', 16, [
          'What Loneliness Actually Is',
          'Why Loneliness Is an Epidemic',
          'Loneliness vs. Being Alone',
          'How Loneliness Affects Your Health',
          'Small Steps Toward Connection',
          'When Digital Connection Helps & When It Doesn\'t',
          'Reaching Out When It\'s Hard',
          'Building a Less Lonely Life',
        ]),
      },
      {
        id: '3-17', pillarId: '3', number: 17,
        title: 'Social Media & Mental Health',
        description: 'How social media affects your brain, your mood, and your sense of self — and what to do about it.',
        emoji: '📱', unlocked: true, completed: false,
        lessons: makeLessons('3', 17, [
          'How Social Media Is Designed to Affect You',
          'Comparison Culture & What It Does to Your Brain',
          'Doomscrolling & Anxiety',
          'FOMO — What It Is & How to Manage It',
          'Setting Healthy Limits With Social Media',
          'Digital Detox — How & When to Do It',
          'Curating Your Feed for Your Mental Health',
          'Using Social Media Intentionally',
        ]),
      },
      {
        id: '3-18', pillarId: '3', number: 18,
        title: 'Therapy — What It Is & How to Access It',
        description: 'Demystifying therapy, what to expect, and how to find help you can actually afford.',
        emoji: '💬', unlocked: true, completed: false,
        lessons: makeLessons('3', 18, [
          'What Therapy Actually Is',
          'Types of Therapy — CBT, DBT, Talk Therapy & More',
          'How to Know If You Need Therapy',
          'Finding a Therapist',
          'What to Expect in Your First Session',
          'How to Afford Therapy',
          'Online Therapy — Pros & Cons',
          'What to Do If Therapy Isn\'t Working',
        ]),
      },
      {
        id: '3-19', pillarId: '3', number: 19,
        title: 'Medication & Mental Health',
        description: 'Understanding psychiatric medication, how it works, and how to navigate it without fear.',
        emoji: '💊', unlocked: true, completed: false,
        lessons: makeLessons('3', 19, [
          'What Psychiatric Medication Is',
          'Common Types of Medication & What They Do',
          'How to Talk to Your Doctor About Medication',
          'Starting Medication — What to Expect',
          'Side Effects — What\'s Normal & What\'s Not',
          'Medication & Therapy Together',
          'Going Off Medication — How to Do It Safely',
          'Stigma Around Medication & How to Handle It',
        ]),
      },
      {
        id: '3-20', pillarId: '3', number: 20,
        title: 'Substance Use & Addiction Awareness',
        description: 'Understanding substance use, addiction, and how to get help for yourself or someone you love.',
        emoji: '🫂', unlocked: true, completed: false,
        lessons: makeLessons('3', 20, [
          'Understanding Substance Use',
          'How Addiction Works in the Brain',
          'Signs of a Substance Use Problem',
          'Alcohol — The Most Normalized Drug',
          'Prescription Drug Misuse',
          'How to Talk to Someone You\'re Worried About',
          'Getting Help — Treatment Options',
          'Recovery — What It Looks Like & What It Takes',
        ]),
      },
      {
        id: '3-21', pillarId: '3', number: 21,
        title: 'Body Image & Self-Care',
        description: 'Building a healthier relationship with your body and understanding what real self-care looks like.',
        emoji: '🌸', unlocked: true, completed: false,
        lessons: makeLessons('3', 21, [
          'Where Body Image Comes From',
          'Media & the Unrealistic Standard',
          'Diet Culture — What It Is & Why It\'s Harmful',
          'Building Body Neutrality',
          'What Self-Care Actually Means',
          'Physical Self-Care — Movement, Food & Rest',
          'Emotional Self-Care',
          'Self-Care on a Budget',
        ]),
      },
      {
        id: '3-22', pillarId: '3', number: 22,
        title: 'Purpose & Identity',
        description: 'Figuring out who you are outside of what you do and building a life with meaning.',
        emoji: '🧭', unlocked: true, completed: false,
        lessons: makeLessons('3', 22, [
          'Who Are You Outside of Work',
          'Values — What Yours Actually Are',
          'Identity & How It Shifts Over Time',
          'Finding Purpose Without a Grand Vision',
          'The Role of Passion vs. Meaning',
          'Building a Life That Reflects Who You Are',
          'When You Feel Lost',
          'Reinvention — It\'s Always Possible',
        ]),
      },
      {
        id: '3-23', pillarId: '3', number: 23,
        title: 'Forgiveness',
        description: 'What forgiveness actually is, why it matters for you, and how to practice it.',
        emoji: '🤍', unlocked: true, completed: false,
        lessons: makeLessons('3', 23, [
          'What Forgiveness Is & Isn\'t',
          'Why Holding Onto Resentment Hurts You',
          'Forgiving Someone Who Hasn\'t Apologized',
          'Self-Forgiveness — The Hardest Kind',
          'The Process of Forgiveness',
          'When Forgiveness Doesn\'t Mean Reconciliation',
          'Forgiveness in the Context of Trauma',
          'Moving Forward After Forgiving',
        ]),
      },
      {
        id: '3-24', pillarId: '3', number: 24,
        title: 'Mindfulness & Being Present',
        description: 'What mindfulness is, why it matters, and how to actually practice it in real life.',
        emoji: '🧘', unlocked: true, completed: false,
        lessons: makeLessons('3', 24, [
          'What Mindfulness Actually Is',
          'Why Being Present Is So Hard',
          'Mindfulness vs. Meditation — What\'s the Difference',
          'Simple Mindfulness Practices for Daily Life',
          'Mindful Eating',
          'Mindful Communication',
          'Mindfulness for Anxiety & Stress',
          'Building a Consistent Practice',
        ]),
      },
      {
        id: '3-25', pillarId: '3', number: 25,
        title: 'Building Resilience',
        description: 'What resilience is, how it\'s built, and how to bounce back from anything.',
        emoji: '🌳', unlocked: true, completed: false,
        lessons: makeLessons('3', 25, [
          'What Resilience Actually Is',
          'Resilience Is Built, Not Born',
          'The Role of Adversity in Growth',
          'Post-Traumatic Growth — Real & Possible',
          'Building Your Resilience Toolkit',
          'Community as a Resilience Factor',
          'When to Push Through & When to Rest',
          'Your Story Is Not Over',
        ]),
      },
    ],
  },

  // ─────────────────────────────────────────
  // PILLAR 4 — CRISIS MANAGEMENT
  // ─────────────────────────────────────────
  {
    id: '4',
    number: 4,
    title: 'Crisis Management',
    description: 'The life events nobody prepares you for — getting a job, losing a job, having a baby, legal trouble, incarceration, homelessness, and everything in between.',
    emoji: '🆘',
    modules: [
      {
        id: '4-1', pillarId: '4', number: 1,
        title: 'I Just Got a Job — What Do I Do Now',
        description: 'The immediate practical steps to take when you land a job so you start strong.',
        emoji: '🎉', unlocked: true, completed: false,
        lessons: makeLessons('4', 1, [
          'Congratulations — Now What',
          'Paperwork You\'ll Fill Out on Day One',
          'Setting Up Direct Deposit',
          'Understanding Your Offer Letter',
          'What to Wear, When to Show Up & How to Act',
          'Your First Week — How to Make a Good Impression',
          'Building Relationships at Work Early',
          'Setting Yourself Up for a Review & Raise',
        ]),
      },
      {
        id: '4-2', pillarId: '4', number: 2,
        title: 'I Just Got Fired — What Do I Do Now',
        description: 'The immediate steps to take after losing a job — financially, emotionally, and practically.',
        emoji: '😮', unlocked: true, completed: false,
        lessons: makeLessons('4', 2, [
          'The First 24 Hours',
          'Filing for Unemployment — How & When',
          'Understanding Your Severance If You Got One',
          'COBRA — Keeping Your Health Insurance',
          'Updating Your Budget for No Income',
          'Telling People You Were Fired',
          'Processing the Emotional Side',
          'Getting Back on Your Feet',
        ]),
      },
      {
        id: '4-3', pillarId: '4', number: 3,
        title: 'How to Find a Job',
        description: 'A practical guide to job searching that actually works in today\'s market.',
        emoji: '🔍', unlocked: true, completed: false,
        lessons: makeLessons('4', 3, [
          'Knowing What You Want',
          'Where to Actually Find Jobs',
          'Networking — How to Do It Without Feeling Fake',
          'Applying — Quality vs. Quantity',
          'Following Up Without Being Annoying',
          'Dealing With Rejection During the Search',
          'Job Search Burnout — How to Avoid It',
          'Evaluating an Offer When It Comes',
        ]),
      },
      {
        id: '4-4', pillarId: '4', number: 4,
        title: 'Writing a Resume From Scratch',
        description: 'How to build a resume that gets noticed even when you don\'t have much experience.',
        emoji: '📝', unlocked: true, completed: false,
        lessons: makeLessons('4', 4, [
          'What a Resume Actually Does',
          'The Parts of a Resume',
          'Writing With No Experience',
          'Action Words That Work',
          'Tailoring Your Resume to Each Job',
          'Formatting — What Works & What Doesn\'t',
          'Common Resume Mistakes',
          'Cover Letters — When You Need One & How to Write It',
        ]),
      },
      {
        id: '4-5', pillarId: '4', number: 5,
        title: 'Nailing the Interview',
        description: 'How to prepare for, show up to, and follow up after a job interview.',
        emoji: '🎯', unlocked: true, completed: false,
        lessons: makeLessons('4', 5, [
          'Types of Interviews',
          'Researching the Company Before You Go',
          'Common Interview Questions & How to Answer Them',
          'The STAR Method for Behavioral Questions',
          'What to Wear & How to Show Up',
          'Questions to Ask Them',
          'After the Interview — Following Up',
          'When You Don\'t Get It',
        ]),
      },
      {
        id: '4-6', pillarId: '4', number: 6,
        title: 'Negotiating a Job Offer',
        description: 'How to evaluate a job offer and negotiate for what you deserve.',
        emoji: '💰', unlocked: true, completed: false,
        lessons: makeLessons('4', 6, [
          'Reading the Offer Letter',
          'What\'s Negotiable Beyond Salary',
          'How to Counter Offer',
          'Negotiating Remotely or in Writing',
          'What to Do If They Won\'t Budge',
          'Accepting & Declining Professionally',
          'Start Date Negotiation',
          'Getting It in Writing',
        ]),
      },
      {
        id: '4-7', pillarId: '4', number: 7,
        title: 'I Just Had a Baby — What Do I Do Now',
        description: 'The immediate practical steps new parents need to take in the first days and weeks.',
        emoji: '👶', unlocked: true, completed: false,
        lessons: makeLessons('4', 7, [
          'The First 72 Hours',
          'Getting a Social Security Number for Your Baby',
          'Adding Your Baby to Your Health Insurance',
          'Parental Leave — How to Use It',
          'Birth Certificate & Legal Documents',
          'WIC, Medicaid & Benefits You May Qualify For',
          'Childcare — Starting to Plan Now',
          'Adjusting Your Budget for a New Person',
        ]),
      },
      {
        id: '4-8', pillarId: '4', number: 8,
        title: 'Navigating Parental Leave',
        description: 'Understanding your rights, your pay, and how to actually use parental leave.',
        emoji: '🍼', unlocked: true, completed: false,
        lessons: makeLessons('4', 8, [
          'What Parental Leave Is',
          'FMLA — What It Covers & Who Qualifies',
          'Paid vs. Unpaid Leave',
          'State Paid Leave Programs',
          'Talking to Your Employer About Leave',
          'Planning Financially for Unpaid Leave',
          'Returning to Work After Leave',
          'Your Rights When You Come Back',
        ]),
      },
      {
        id: '4-9', pillarId: '4', number: 9,
        title: 'Single Parenting on a Budget',
        description: 'How to manage money, time, and everything else when you\'re doing it alone.',
        emoji: '💪', unlocked: true, completed: false,
        lessons: makeLessons('4', 9, [
          'The Reality of Single Parenting',
          'Child Support — How It Works',
          'Government Assistance Available to Single Parents',
          'Childcare Costs & Options',
          'Budgeting for Two on One Income',
          'Building a Support System as a Single Parent',
          'Time Management With Kids',
          'Taking Care of Yourself So You Can Take Care of Them',
        ]),
      },
      {
        id: '4-10', pillarId: '4', number: 10,
        title: 'My Car Broke Down — What Do I Do Now',
        description: 'What to do in the moment and the steps after when your car stops working.',
        emoji: '🚨', unlocked: true, completed: false,
        lessons: makeLessons('4', 10, [
          'Immediate Safety Steps',
          'Calling for Help — AAA, Roadside Assistance, Friends',
          'Getting Your Car to a Shop',
          'Understanding the Diagnosis',
          'Getting a Second Opinion',
          'When to Repair vs. Replace',
          'Paying for an Unexpected Repair',
          'Preventing It From Happening Again',
        ]),
      },
      {
        id: '4-11', pillarId: '4', number: 11,
        title: 'I Got Into a Car Accident — What Do I Do Now',
        description: 'Step by step what to do at the scene and after a car accident.',
        emoji: '💥', unlocked: true, completed: false,
        lessons: makeLessons('4', 11, [
          'Immediate Steps at the Scene',
          'What to Say & What Not to Say',
          'Exchanging Information',
          'Filing a Police Report',
          'Contacting Your Insurance',
          'Getting a Rental Car',
          'Dealing With the Other Driver\'s Insurance',
          'When to Get a Lawyer',
        ]),
      },
      {
        id: '4-12', pillarId: '4', number: 12,
        title: 'I\'m Being Evicted — What Do I Do Now',
        description: 'Understanding the eviction process, your rights, and what to do at every stage.',
        emoji: '🏚️', unlocked: true, completed: false,
        lessons: makeLessons('4', 12, [
          'How Eviction Actually Works',
          'Your Rights During the Eviction Process',
          'Responding to an Eviction Notice',
          'Going to Eviction Court',
          'Emergency Rental Assistance Programs',
          'Negotiating With Your Landlord',
          'If You Have to Leave — What to Do',
          'Life After Eviction — Finding Housing With an Eviction on Your Record',
        ]),
      },
      {
        id: '4-13', pillarId: '4', number: 13,
        title: 'I Can\'t Pay My Bills — What Do I Do Now',
        description: 'What to do when you have more bills than money and how to prioritize.',
        emoji: '😰', unlocked: true, completed: false,
        lessons: makeLessons('4', 13, [
          'The First Thing to Do — Stop Panicking',
          'Prioritizing Bills — What to Pay First',
          'Calling Your Creditors Before You Miss a Payment',
          'Hardship Programs — What They Are & How to Ask',
          'Government Assistance — What\'s Available',
          'Community Resources — Food Banks, Utilities Help',
          'Payday Loans — Why to Avoid Them',
          'Making a Plan to Get Back on Track',
        ]),
      },
      {
        id: '4-14', pillarId: '4', number: 14,
        title: 'I Lost My Health Insurance — What Do I Do Now',
        description: 'Your options when you lose health insurance and how to get covered fast.',
        emoji: '🏥', unlocked: true, completed: false,
        lessons: makeLessons('4', 14, [
          'Why You Lost It & What That Means',
          'COBRA — What It Is & Whether It\'s Worth It',
          'Marketplace Insurance & Special Enrollment',
          'Medicaid — Do You Qualify Now',
          'Short-Term Health Plans — Pros & Cons',
          'Community Health Centers — Free & Low Cost Care',
          'Prescription Coverage Without Insurance',
          'Getting Covered Before Something Goes Wrong',
        ]),
      },
      {
        id: '4-15', pillarId: '4', number: 15,
        title: 'I\'m Going Through a Divorce or Breakup — What Do I Do Now',
        description: 'The practical and emotional steps to take when a serious relationship ends.',
        emoji: '💔', unlocked: true, completed: false,
        lessons: makeLessons('4', 15, [
          'The First Days — What to Prioritize',
          'Separating Your Finances',
          'Closing or Changing Joint Accounts',
          'Legal Separation vs. Divorce',
          'Finding a Lawyer or Using Mediation',
          'Division of Assets & Debt',
          'Child Custody Basics',
          'Rebuilding Your Financial Life Alone',
          'The Emotional Process & Getting Support',
        ]),
      },
      {
        id: '4-16', pillarId: '4', number: 16,
        title: 'I Just Lost Someone — Grief & Practical Next Steps',
        description: 'What to do in the days and weeks after someone close to you dies.',
        emoji: '🕊️', unlocked: true, completed: false,
        lessons: makeLessons('4', 16, [
          'The First 24-48 Hours',
          'Death Certificates & Why You Need Multiple Copies',
          'Notifying Institutions — Banks, Social Security, Employers',
          'Estate & Will — What Happens Next',
          'Handling Their Bills & Accounts',
          'Funeral Costs & How to Manage Them',
          'Grief Leave & Your Rights at Work',
          'Taking Care of Yourself While Managing Everything',
        ]),
      },
      {
        id: '4-17', pillarId: '4', number: 17,
        title: 'I\'m in Legal Trouble — What Do I Do Now',
        description: 'What to do when you\'re facing legal charges or involvement in the legal system.',
        emoji: '⚖️', unlocked: true, completed: false,
        lessons: makeLessons('4', 17, [
          'Stay Calm — What to Do in the Moment',
          'Your Rights — What You Must Know',
          'The Right to Remain Silent — Use It',
          'Getting a Lawyer — Public Defender vs. Private',
          'Understanding Charges & What They Mean',
          'Bail — What It Is & How It Works',
          'Plea Deals — What They Are & Whether to Take One',
          'What to Tell Your Employer',
        ]),
      },
      {
        id: '4-18', pillarId: '4', number: 18,
        title: 'I\'m Going to Jail or Prison — What Do I Do Now',
        description: 'Practical steps to take before you go in to protect yourself and your life on the outside.',
        emoji: '🔒', unlocked: true, completed: false,
        lessons: makeLessons('4', 18, [
          'Getting Your Affairs in Order',
          'Power of Attorney — What It Is & Why You Need It',
          'Your Kids — Making Arrangements',
          'Your Housing & Belongings',
          'Your Bills & Finances While You\'re Away',
          'Staying Connected With Family',
          'What to Expect Inside',
          'Preparing Mentally for the Experience',
        ]),
      },
      {
        id: '4-19', pillarId: '4', number: 19,
        title: 'I Just Got Out of Jail or Prison — What Do I Do Now',
        description: 'The immediate and long-term steps to rebuild your life after incarceration.',
        emoji: '🌅', unlocked: true, completed: false,
        lessons: makeLessons('4', 19, [
          'The First 72 Hours',
          'Getting ID & Essential Documents',
          'Housing — Where to Go When You Have Nothing',
          'Finding Work With a Record',
          'Benefits You May Qualify For',
          'Parole & Probation — Staying Compliant',
          'Rebuilding Relationships',
          'Mental Health After Incarceration',
          'Building a Life That Keeps You Out',
        ]),
      },
      {
        id: '4-20', pillarId: '4', number: 20,
        title: 'I Was Just Released From a Medical Hold — What Do I Do Now',
        description: 'What to do in the days after a psychiatric hospitalization to stay stable and move forward.',
        emoji: '🩺', unlocked: true, completed: false,
        lessons: makeLessons('4', 20, [
          'The First 48 Hours at Home',
          'Following Your Discharge Plan',
          'Medications — Getting Them & Taking Them',
          'Scheduling Follow-Up Care',
          'Telling the People in Your Life',
          'Returning to Work or School',
          'What to Do If You Feel Yourself Slipping',
          'Building a Safety Plan',
        ]),
      },
      {
        id: '4-21', pillarId: '4', number: 21,
        title: 'I\'m Experiencing Domestic Violence — What Do I Do Now',
        description: 'Understanding domestic violence, recognizing it, and getting out safely.',
        emoji: '🆘', unlocked: true, completed: false,
        lessons: makeLessons('4', 21, [
          'What Domestic Violence Actually Is',
          'Why Leaving Is Complicated',
          'Safety Planning — Before You Leave',
          'Emergency Steps When You Need to Leave Now',
          'Domestic Violence Shelters & Resources',
          'Legal Protection — Restraining Orders',
          'Financial Separation & Getting Back on Your Feet',
          'Healing After Domestic Violence',
        ]),
      },
      {
        id: '4-22', pillarId: '4', number: 22,
        title: 'I\'m Homeless or About to Be — What Do I Do Now',
        description: 'Immediate steps to take when you have nowhere to go or are about to lose your housing.',
        emoji: '🏠', unlocked: true, completed: false,
        lessons: makeLessons('4', 22, [
          'If You Have a Few Days — What to Do First',
          'Emergency Shelter — How to Find It',
          'What to Bring & What to Store',
          'Food Access — Food Banks, Soup Kitchens, SNAP',
          'Staying Safe While Homeless',
          'Getting Mail & Staying Connected',
          'Resources Specifically for Your Situation',
          'Getting Back Into Stable Housing',
        ]),
      },
      {
        id: '4-23', pillarId: '4', number: 23,
        title: 'I\'m Struggling With Addiction — What Do I Do Now',
        description: 'Recognizing you have a problem and finding the path to getting help.',
        emoji: '🫂', unlocked: true, completed: false,
        lessons: makeLessons('4', 23, [
          'Admitting It to Yourself',
          'Understanding What You\'re Dealing With',
          'Telling Someone You Trust',
          'Types of Treatment & What to Expect',
          'Detox — What It Is & When It\'s Necessary',
          'Insurance & Paying for Treatment',
          'What Recovery Actually Looks Like',
          'Supporting Yourself Long-Term',
        ]),
      },
      {
        id: '4-24', pillarId: '4', number: 24,
        title: 'I Was Just Diagnosed With Something Serious — What Do I Do Now',
        description: 'How to process a serious diagnosis and navigate the medical, financial, and emotional aftermath.',
        emoji: '🩻', unlocked: true, completed: false,
        lessons: makeLessons('4', 24, [
          'The First Days After a Diagnosis',
          'Understanding Your Diagnosis',
          'Getting a Second Opinion',
          'Navigating the Healthcare System',
          'Insurance, Costs & Financial Assistance',
          'Telling Family & Friends',
          'Mental Health After a Diagnosis',
          'Building Your Care Team & Support System',
        ]),
      },
      {
        id: '4-25', pillarId: '4', number: 25,
        title: 'I\'m a Caregiver for a Family Member — What Do I Do Now',
        description: 'How to care for someone else without destroying your own health, finances, and sanity.',
        emoji: '❤️', unlocked: true, completed: false,
        lessons: makeLessons('4', 25, [
          'Understanding What You\'ve Taken On',
          'Legal Authority — Power of Attorney & Guardianship',
          'Financial Management for Someone Else',
          'Navigating Their Healthcare',
          'Government Benefits Available to Caregivers',
          'Balancing Caregiving With Your Own Life',
          'Caregiver Burnout — Recognizing & Preventing It',
          'When You Can No Longer Do It Alone',
        ]),
      },
      {
        id: '4-26', pillarId: '4', number: 26,
        title: 'I\'m Aging Out of Foster Care — What Do I Do Now',
        description: 'A guide specifically for young people leaving foster care and navigating the world alone.',
        emoji: '🌱', unlocked: true, completed: false,
        lessons: makeLessons('4', 26, [
          'What Aging Out Means',
          'Extended Foster Care — Are You Eligible',
          'Housing Options After Foster Care',
          'Education Benefits Available to Former Foster Youth',
          'Financial Assistance & Benefits',
          'Getting Your Documents — ID, Birth Certificate, Social Security',
          'Building a Support System From Scratch',
          'You Are Not Alone — Community & Resources',
        ]),
      },
      {
        id: '4-27', pillarId: '4', number: 27,
        title: 'I\'m an Immigrant or Refugee — Navigating Systems in the US',
        description: 'Understanding how to access services, know your rights, and build stability in a new country.',
        emoji: '🌍', unlocked: true, completed: false,
        lessons: makeLessons('4', 27, [
          'Understanding Your Immigration Status',
          'Your Rights Regardless of Status',
          'Getting a Social Security Number',
          'Healthcare Access for Immigrants',
          'Education Rights for Immigrant Children',
          'Finding Work Legally',
          'Sending Money Home — Safely & Affordably',
          'Community Resources & Legal Aid',
        ]),
      },
      {
        id: '4-28', pillarId: '4', number: 28,
        title: 'I Just Filed for Bankruptcy — What Do I Do Now',
        description: 'What happens after bankruptcy, how to rebuild, and how to move forward.',
        emoji: '📋', unlocked: true, completed: false,
        lessons: makeLessons('4', 28, [
          'What Bankruptcy Actually Does',
          'Chapter 7 vs. Chapter 13 — What You Filed & What It Means',
          'What Happens to Your Debt',
          'What Happens to Your Assets',
          'Life During Bankruptcy — What You Can & Can\'t Do',
          'Rebuilding Your Credit After Bankruptcy',
          'Getting Housing After Bankruptcy',
          'The Financial Fresh Start — How to Use It',
        ]),
      },
      {
        id: '4-29', pillarId: '4', number: 29,
        title: 'My Identity Was Stolen — What Do I Do Now',
        description: 'Step by step what to do when your identity has been compromised.',
        emoji: '🔐', unlocked: true, completed: false,
        lessons: makeLessons('4', 29, [
          'Recognizing Identity Theft',
          'The First Steps — Move Fast',
          'Placing a Fraud Alert & Credit Freeze',
          'Reporting to the FTC',
          'Disputing Fraudulent Accounts',
          'Dealing With Debt Collectors for Fraud',
          'Recovering Your Credit',
          'Preventing It From Happening Again',
        ]),
      },
      {
        id: '4-30', pillarId: '4', number: 30,
        title: 'I\'m Being Stalked or Harassed — What Do I Do Now',
        description: 'How to recognize stalking and harassment, document it, and get help.',
        emoji: '🛡️', unlocked: true, completed: false,
        lessons: makeLessons('4', 30, [
          'What Stalking & Harassment Actually Are',
          'Documenting Everything',
          'Online Stalking & Harassment',
          'Telling Someone — Who & How',
          'Getting a Restraining Order',
          'Safety Planning',
          'Working With Law Enforcement',
          'Healing & Moving Forward',
        ]),
      },
      {
        id: '4-31', pillarId: '4', number: 31,
        title: 'Natural Disaster Recovery — What Do I Do Now',
        description: 'What to do in the aftermath of a natural disaster to get back on your feet.',
        emoji: '🌪️', unlocked: true, completed: false,
        lessons: makeLessons('4', 31, [
          'Immediate Safety After a Disaster',
          'Contacting Family & Letting People Know You\'re Safe',
          'FEMA — What It Is & How to Apply',
          'Insurance Claims After a Disaster',
          'Temporary Housing Options',
          'Financial Assistance Available',
          'Mental Health After a Disaster',
          'Rebuilding — Short-Term & Long-Term',
        ]),
      },
      {
        id: '4-32', pillarId: '4', number: 32,
        title: 'I Need to Leave Quickly — Emergency Planning & Safety',
        description: 'How to plan for and execute a safe, fast exit from a dangerous situation.',
        emoji: '🏃', unlocked: true, completed: false,
        lessons: makeLessons('4', 32, [
          'Recognizing When You Need to Leave',
          'Building a Go-Bag',
          'Important Documents to Have Ready',
          'Where to Go',
          'Telling the Right People',
          'Financial Access When You Leave in a Hurry',
          'Staying Safe After You Leave',
          'Resources That Can Help',
        ]),
      },
    ],
  },
]

// ─── Helpers ───────────────────────────────
export function getPillar(pillarId: string): Pillar | undefined {
  return pillars.find(p => p.id === pillarId)
}

export function getModule(moduleId: string): Module | undefined {
  for (const pillar of pillars) {
    const mod = pillar.modules.find(m => m.id === moduleId)
    if (mod) return mod
  }
  return undefined
}

export function getLesson(moduleId: string, lessonNumber: number): { lesson: Lesson; module: Module; pillar: Pillar } | undefined {
  for (const pillar of pillars) {
    const mod = pillar.modules.find(m => m.id === moduleId)
    if (mod) {
      const lesson = mod.lessons[lessonNumber - 1]
      if (lesson) return { lesson, module: mod, pillar }
    }
  }
  return undefined
}

export const totalModules = pillars.reduce((acc, p) => acc + p.modules.length, 0)
export const totalLessons = pillars.reduce((acc, p) => p.modules.reduce((a, m) => a + m.lessons.length, acc), 0)
